package com.cometproject.api.game.achievements.types;

public enum AchievementType {
    /*AVATAR_LOOKS("ACH_AvatarLooks"),
    MOTTO("ACH_Motto"),
    RESPECT_GIVEN("ACH_RespectGiven"),
    RESPECT_EARNED("ACH_RespectEarned"),
    ROOM_ENTRY("ACH_RoomEntry"),
    REGISTRATION_DURATION("ACH_RegistrationDuration"),
    PET_RESPECT_GIVEN("ACH_PetRespectGiver"),
    PET_LOVER("ACH_PetLover"),
    GIFT_GIVER("ACH_GiftGiver"),
    GIFT_RECEIVER("ACH_GiftReceiver"),
    BB_TILES_LOCKED("ACH_BattleBallTilesLocked"),
    BB_PLAYER("ACH_BattleBallPlayer"),
    BB_WINNER("ACH_BattleBallWinner"),
    ONLINE_TIME("ACH_AllTimeHotelPresence"),
    LOGIN("ACH_Login"),
    FRIENDS_LIST("ACH_FriendListSize"),
    CAMERA_PHOTO("ACH_CameraPhotoCount"),
    FOOTBALL_GOAL("ACH_FootballGoalScoredInRoom");*/

    ACH_1("ACH_AlexandraFound"),
    ACH_2("ACH_AllTimeHotelPresence"),
    ACH_3("ACH_AvatarLooks"),
    ACH_4("ACH_BaseJumpBigParachute"),
    ACH_5("ACH_BaseJumpDaysPlayed"),
    ACH_6("ACH_BaseJumpMissile"),
    ACH_7("ACH_BaseJumpShield"),
    ACH_8("ACH_BaseJumpWins"),
    ACH_9("ACH_BattleBallPlayer"),
    ACH_10("ACH_BattleBallTilesLocked"),
    ACH_11("ACH_BattleBallWinner"),
    ACH_12("ACH_CameraPhotoCount"),
    ACH_13("ACH_ChessPlayed"),
    ACH_14("ACH_ChessWinner"),
    ACH_15("ACH_Citizenship"),
    ACH_16("ACH_Crafting"),
    ACH_17("ACH_CrystalCracker"),
    ACH_18("ACH_EggCracker"),
    ACH_19("ACH_Farmer"),
    ACH_20("ACH_FILWinner"),
    ACH_21("ACH_FootballGoalScored"),
    ACH_22("ACH_Forum"),
    ACH_23("ACH_FriendListSize"),
    ACH_24("ACH_GeneralBet"),
    ACH_25("ACH_GiftGiver"),
    ACH_26("ACH_GiftReceiver"),
    ACH_27("ACH_GuideEnrollmentLifetime"),
    ACH_28("ACH_GuideRecommendation"),
    ACH_29("ACH_GuideTourGiver"),
    ACH_30("ACH_HeartBet"),
    ACH_31("ACH_Login"),
    ACH_32("ACH_LTDPurchased"),
    ACH_33("ACH_Motto"),
    ACH_34("ACH_Name"),
    ACH_35("ACH_PetLevelUp"),
    ACH_36("ACH_PetLover"),
    ACH_37("ACH_PetRespectGiver"),
    ACH_38("ACH_PetRespectReceiver"),
    ACH_39("ACH_PinataBreaker"),
    ACH_40("ACH_PinataWhacker"),
    ACH_41("ACH_RegistrationDuration"),
    ACH_42("ACH_RespectEarned"),
    ACH_43("ACH_RespectGiven"),
    ACH_44("ACH_RoomDecoFloor"),
    ACH_45("ACH_RoomDecoFurniCount"),
    ACH_46("ACH_RoomDecoLandscape"),
    ACH_47("ACH_RoomDecoWallpaper"),
    ACH_48("ACH_RoomEntry"),
    ACH_49("ACH_SelfModBanSeen"),
    ACH_50("ACH_SelfModChatFloodFilterSeen"),
    ACH_51("ACH_SelfModChatHearRangeSeen"),
    ACH_52("ACH_SelfModChatScrollSpeedSeen"),
    ACH_53("ACH_SelfModDoorModeSeen"),
    ACH_54("ACH_SelfModForumCanModerateSeen"),
    ACH_55("ACH_SelfModForumCanPostSeen"),
    ACH_56("ACH_SelfModForumCanPostThrdSeen"),
    ACH_57("ACH_SelfModForumCanReadSeen"),
    ACH_58("ACH_SelfModIgnoreSeen"),
    ACH_59("ACH_SelfModKickSeen"),
    ACH_60("ACH_SelfModMuteSeen"),
    ACH_61("ACH_SelfModRoomFilterSeen"),
    ACH_62("ACH_SelfModWalkthroughSeen"),
    ACH_63("ACH_SkullBet"),
    ACH_64("ACH_StarBet"),
    ACH_65("ACH_ViciousViking"),
    ACH_66("ACH_SoKKiller"),
    ACH_67("ACH_SoKSaver"),
    ACH_68("ACH_SoKWinner"),
    ACH_69("ACH_snowBoardBuild"),
    ACH_70("ACH_RoomDecoFurniTypeCount"),
    ACH_71("ACH_RoomDecoHoleFurniCount"),
    ACH_72("ACH_RoomDecoHosting"),
    ACH_73("ACH_NotesReceived"),
    ACH_74("ACH_NotesLeft"),
    ACH_75("ACH_FireworksCharger"),
    ACH_76("ACH_BearBreeder"),
    ACH_77("ACH_FreezeWinner"),
    ACH_78("ACH_FreezePowerUp"),
    ACH_79("ACH_FreezePlayer"),
    ACH_80("ACH_HorseConsecutiveJumpsCount"),
    ACH_81("ACH_GnomeRespectGiver"),
    ACH_82("ACH_GnomeLevelUp"),
    ACH_83("ACH_GnomeFeeding"),
    ACH_84("ACH_LeprechaunRespectGiver"),
    ACH_85("ACH_LeprechaunLevelUp"),
    ACH_86("ACH_LeprechaunFeeding"),
    ACH_87("ACH_MusicPlayer"),
    ACH_88("ACH_MusicCollector"),
    ACH_89("ACH_RbTagC"),
    ACH_90("ACH_RbTagA"),
    ACH_91("ACH_RbBunnyTag"),
    ACH_92("ACH_Spr"),
    ACH_93("ACH_EsA"),
    ACH_94("ACH_FreezeQuestCompleted"),
    ACH_95("ACH_AnimationRanking"),
    ACH_96("ACH_CasinoBeWinner"),
    ACH_97("ACH_HabboRoue"),
    ACH_98("ACH_HabboChat"),
    ACH_99("ACH_HabboMotto"),
    ACH_100("ACH_HabboName"),
    ACH_101("ACH_EventHost"),
    ACH_102("ACH_KissHabbo"),
    ACH_103("ACH_HabboTag"),
    ACH_104("ACH_SurvivalBullets"),
    ACH_105("ACH_SurvivalChest"),
    ACH_106("ACH_SurvivalKills"),
    ACH_107("ACH_VipClub"),
    ACH_108("ACH_GameSeasonalPass"),
    ACH_109("ACH_SafetyQuizGraduate"),
    ACH_110("ACH_BitePlayer"),
    ACH_111("ACH_ThreatPlayer"),
    ACH_112("ACH_ThrowCandy"),
    ACH_113("ACH_RoulletteBig"),
    ACH_114("ACH_RoulletteColor"),
    ACH_115("ACH_RoulletteFree"),
    ACH_116("ACH_RoulletteRow"),
    ACH_117("ACH_RoulletteStandard"),
    ACH_118("ACH_RoulletteZero"),
    ACH_119("ACH_StealCoffee"),
    ACH_120("ACH_BurnWeen"),
    ACH_121("ACH_PukeWeen"),
    ACH_122("ACH_RPSGame"),
    ACH_123("ACH_VikingSlay"),
    ACH_124("ACH_VikingBurp"),
    ACH_125("ACH_BottleShuffle"),
    ACH_126("ACH_GuideRequestHandler"),
    ACH_127("ACH_GuideRecommendation"),
    ACH_128("ACH_SurvivalWinner"),
    ACH_129("ACH_RPS"),
    ACH_130("ACH_EggThrower"),
    ACH_131("ACH_Horticulturist"),
    ACH_132("ACH_HealingDone"),
    ACH_133("ACH_RobberyDone"),
    ACH_134("ACH_FishingDone");

    private String groupName;

    AchievementType(String groupName) {
        this.groupName = groupName;
    }

    public String getGroupName() {
        return groupName;
    }

    public static AchievementType getTypeByName(String name) {
        for (AchievementType type : AchievementType.values()) {
            if (type.groupName.equals(name)) {
                return type;
            }
        }

        return null;
    }
}
